sudo: false
cache: bundler
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - make test
